# Generated by Django 5.2.7 on 2025-11-18 18:31

import apps.programsapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReviewTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('stage1', '一审'), ('stage2', '二审'), ('stage3', '三审'), ('completed', '已完成')], default='stage1', max_length=32)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤销')], default='pending', max_length=32)),
                ('review_notes', models.TextField(blank=True)),
                ('review_trail', models.JSONField(blank=True, default=list)),
                ('id', models.CharField(default=apps.programsapp.models.generate_student_ticket_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=128)),
                ('student_id', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=apps.programsapp.models.generate_project_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points', models.FloatField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('slots', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停中'), ('archived', '已归档')], default='active', max_length=32)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('stage1', '一审'), ('stage2', '二审'), ('stage3', '三审'), ('completed', '已完成')], default='stage1', max_length=32)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤销')], default='pending', max_length=32)),
                ('review_notes', models.TextField(blank=True)),
                ('review_trail', models.JSONField(blank=True, default=list)),
                ('id', models.CharField(default=apps.programsapp.models.generate_volunteer_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=128)),
                ('student_account', models.CharField(max_length=128)),
                ('student_id', models.CharField(blank=True, max_length=32)),
                ('activity', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proof', models.CharField(blank=True, max_length=255)),
                ('require_ocr', models.BooleanField(default=False)),
                ('submitted_via', models.CharField(choices=[('student', '学生提交'), ('teacher', '教师创建')], default='student', max_length=32)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_records', to='programsapp.teacherproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSelection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=apps.programsapp.models.generate_selection_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=128)),
                ('student_account', models.CharField(max_length=128)),
                ('student_id', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', '已选择'), ('cancelled', '已取消')], default='active', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='programsapp.teacherproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project', 'student_account'), name='unique_active_selection_per_student')],
            },
        ),
    ]
